User.create(username: "Jody123")
User.create(username: "Serena321")
User.create(username: "Patsy555")
User.create(username: "BobWazHere")
User.create(username: "MyspaceTom")

ContactHistory.create(user_id: 1, business_id: 4)
ContactHistory.create(user_id: 4, business_id: 2)
ContactHistory.create(user_id: 2, business_id: 5)
ContactHistory.create(user_id: 5, business_id: 5)
ContactHistory.create(user_id: 1, business_id: 1)
ContactHistory.create(user_id: 3, business_id: 3)
ContactHistory.create(user_id: 2, business_id: 1)
